# Generated by Django 2.2 on 2019-04-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCAClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(default='', max_length=254)),
                ('comment', models.TextField(default='')),
                ('adress', models.CharField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=45)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
            },
        ),
    ]
