# Generated by Django 2.2 on 2019-04-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCAContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('first_name', models.CharField(max_length=254)),
                ('email', models.EmailField(default='', max_length=254)),
                ('adress', models.CharField(default='', max_length=254)),
                ('phone_1', models.CharField(default='', max_length=45)),
                ('phone_2', models.CharField(default='', max_length=45)),
                ('quality', models.CharField(choices=[('adv', 'Adversaire'), ('ges', 'Gestionnaire'), ('hui', 'Huissier'), ('cor', 'Correspondant')], default='', max_length=45)),
                ('title', models.CharField(choices=[('co', 'Compagnie'), ('gr', 'Groupe'), ('do', 'Docteur'), ('ma', 'Madame'), ('Mt', 'Maitre')], default='', max_length=45)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
            },
        ),
    ]
