# Generated by Django 2.2 on 2019-04-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcaaffaire',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gcaaffaire',
            name='date_open',
            field=models.DateField(),
        ),
    ]
