# Generated by Django 2.2 on 2019-04-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_gcacontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCAAffaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(default='', max_length=254)),
                ('number_case', models.CharField(default='', max_length=254)),
                ('description', models.TextField(default='')),
                ('place', models.CharField(default='', help_text='Lieu', max_length=254)),
                ('nature', models.CharField(choices=[('co', 'Construction'), ('ds', 'Droit de société'), ('ta', 'Transport arérien'), ('da', "Droit d'auteur"), ('au', 'Autres')], default='', max_length=45)),
                ('comment', models.TextField(default='')),
                ('date_open', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
            ],
        ),
    ]
