# Generated by Django 2.2 on 2019-04-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_gcaaffaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcaaffaire',
            options={'verbose_name': 'Affaire', 'verbose_name_plural': 'Affaires'},
        ),
        migrations.AlterModelTable(
            name='gcaaffaire',
            table='affaire',
        ),
    ]
