# Generated by Django 2.2 on 2019-05-05 20:53

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190505_0850'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gcauser',
            managers=[
                ('objects', backend.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='gcauser',
            name='username',
            field=models.CharField(help_text='username', max_length=100, unique=True),
        ),
    ]
