# Generated by Django 2.2 on 2019-05-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190505_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcauser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
