# Generated by Django 2.2 on 2019-05-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190506_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcauser',
            name='username',
        ),
    ]
